baseURL = "http://example.org/"
languageCode = "en-us"
title = "Khushi Tripathi"
theme = "PaperMod"

[params]
  author = "Khushi Tripathi"
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowShareButtons = true
  displayFullLangName = true

  [params.profileMode]
    enabled = true
    title = "Hi, I’m Khushi 👋"
    subtitle = """Data Engineer | Python Whisperer
M.S. Data Science, UB | 2+ YOE
Fluent in Python, sarcasm & structured chaos"""
    imageUrl = "/images/My_Profile.png"
    imageTitle = "Khushi Tripathi"
    imageWidth = 180
    imageHeight = 180
    buttons = [
      { name = "GitHub", url = "https://github.com/Khushitr" },
      { name = "LinkedIn", url = "https://linkedin.com/in/khushi-tripathi" },
      { name = "Email", url = "mailto:tripathikhushi214@gmail.com" }
    ]

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

